### ISSUE TITLE
Generowanie listy recenzentów w części publicznej

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#107]
Zadanie podobne jest do #26 Różnica polega na tym, że lista ta jest dostępna w części publicznej. Ponadto strona ta powinna zawierać listę wszystkich recenzentów. Lista ta powinna być alfabetyczna i nie powinna wskazywać, czy dany recenzent recenzował artykuł przyjęty, czy odrzucony.

Strona powinna również informować kiedy lista była ostatnio aktualizowana. Data ta powinna być tożsama z datą wydania ostatniego numeru.

**Comment by lukikrk** [comment]
Zamawiam!

**Comment by lukikrk** [comment]
zwalniam

**Comment by Grzesiek94** [comment]
biorę
