### ISSUE TITLE
Zgłaszanie konfliktu przy wyborze recenzenta

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#108]
System w momencie, w którym wybierany jest recenzent powinien weryfikować, czy żadna z afiliacji recenzenta nie jest identyczna jak afiliacja któregokolwiek z autorów artykułu. W przypadku wykrycia takiej sytuacji system powinien zabronić przypisania recenzji do zgłoszenia.

Jeśli recenzent, bądź którykolwiek z autorów nie ma przypisanej afiliacji, system również powinien zgłaszać informację o błędzie i uniemożliwić przypisanie recenzji.

Tożsamość afiliacji powinna być weryfikowana na poziomie instytucji (np. uniwersytet), a nie instytutu/katedry. Tzn. dwie osoby uczące na UJ mają taką samą afiliację, nawet jeśli uczą na innych wydziałach.

**Comment by ghost** [comment]
zajmuję
