### ISSUE TITLE
Dodanie w widoku listy zgłoszeń liczby recenzentów

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#109]
W widoku listy zgłoszeń powinna być dodatkowa kolumna, która pokazuje ilu recenzentów
zostało przypisanych do zgłoszenia. Liczba ta powinna uwzględniać jedynie recenzje
o następującym statusie:
- recenzja przyjęta
- recenzja pozytywna
- recenzja negatywna
- do poprawy
- przedłużony termin

**Comment by katt94** [comment]
zajmuję

**Comment by apohllo** [comment]
Dla ostatniej wersji artykułu (`self.article_revisions.last`) policzyć recenzentów o tym statusie.

**Comment by apohllo** [comment]
Żeby zrobić to, najlepiej będzie zdefiniować dla recenzji tzw. scope, o nazwie `in_progress`, który będzie obejmował recenzje, które zostały przyjęte lub już zostały napisane.
http://guides.rubyonrails.org/active_record_querying.html#scopes
