### ISSUE TITLE
Poprawić dodawania afiliacji

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#12]
Obecnie dodanie niepełnej afiliacji (bez instytucji i instytutu) powoduje błąd. Należy naprawić to w taki sposób, aby opuszczenie wartości tych pól powodowało wyświetlenie komunikatu o błędzie. Należy również oznaczyć odpowiednia pola (instytucja i instytut) jako wymagane.

**Comment by hryniawska** [comment]
zgłaszam się do tego zadania

**Comment by apohllo** [comment]
To zadanie jest już częściowo zrobione. To co pozostało do zrobienia to testy przy dodawaniu afiliacji. Należy uwzględnić następujące scenariusze testowe:
- wszystkie pola puste
- uzupełnienie kraju
- uzupełnienie kraju i instytucji
- uzupełnienie kraju, instytucji i wydziału.

Tylko w ostatnim przypadku test powinien zakończyć się sukcesem.

**Comment by apohllo** [comment]
Należy też dodać walidację, tak by przy dodawaniu tej samej afiliacji do danej osoby nie było błędu.

**Comment by hryniawska** [comment]
Nie wiem jak się zabrać za dodanie walidacji, na razie gdy próbuję dodać afiliację do danej osoby wyskakuje mi błąd : 

```
NoMethodError in Affiliations#create
undefined method `id' for "":String
```

 Mogłabym prosić o pomoc?

**Comment by hryniawska** [comment]
Nie potrafię tego błędu naprawić :( ale pojawił się on zanim jeszcze zaczęłam pracować nad tym zadaniem

**Comment by hryniawska** [comment]
Bardzo proszę o pomoc

**Comment by apohllo** [comment]
Hmm, to zadanie jest już częściowo rozwiązane. Sprawdzę czego w nim aktualnie brakuje i dam Pani znać.

**Comment by apohllo** [comment]
Generalnie nie będzie to nic skomplikowanego.

**Comment by hryniawska** [comment]
Tak, tylko, że podczas próby wykonania tego zadania, nie mogłam nic zrobić, ponieważ cały czas wyskakuje błąd przy dodaniu afiliacji :(

**Comment by apohllo** [comment]
A jaki to jest błąd?

**Comment by apohllo** [comment]
ok widzę

**Comment by apohllo** [comment]
czy ma Pani najnowszy kod? Chodzi mi o to, czy było wywoływane `git pull apohllo master`?

**Comment by apohllo** [comment]
Ok, zadaniem będzie polegało na tym, że doda Pani tylko dwa testy:
- jedne, gdy wszystkie dane są uzupełnione poprawnie - sprawdzić czy afiliacja się dodała
- drugi, gdy brakuje jednej informacji (np. wydziału) - sprawdzić że afiliacja się nie dodała

**Comment by hryniawska** [comment]
dziękuję bardzo!! już siadam do testów! :)

**Comment by hryniawska** [comment]
pobrałam wszystkie zmiany... teraz jak wpisuję wszystkie dane do formularza dodania afiliacji, niezależnie, czy dodałam Państwo, czy nie dodałam go, cały czas gdy naciskam "Dodaj" pojawia się komunikat, że " Państwo" nie może być puste :(

**Comment by apohllo** [comment]
Proszę wkleić to co się pojawia w logu aplikacji (w oknie, w którym uruchomion `rails s`) jeśli próbuje Pani dodać nową afiliację.

**Comment by apohllo** [comment]
Przykładowo u mnie wygląda to tak:

```
Started POST "/affiliations" for 127.0.0.1 at 2016-03-03 10:42:12 +0100
Processing by AffiliationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"63FRgu1y2irWrCdhbwwvPXw13/1HHE1mIjvFOQgH8YxS2KoEX+HkFonyIlctSISei6ZtQLDu5dbfOcVAgqphiw==", "affiliation_composite"=>{"person_id"=>"17", "country_label"=>"Polska", "country"=>"Polska", "institution_label"=>"Uniwersytet Jagielloński", "institution"=>"Uniwersytet Jagielloński", "department_label"=>"Wydział Filozoficzny", "department"=>"Wydział Filozoficzny", "year_from"=>"", "year_to"=>""}, "commit"=>"Dodaj"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Unpermitted parameters: country_label, institution_label, department_label
  Person Load (0.2ms)  SELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT 1  [["id", 17]]
  Country Load (0.2ms)  SELECT  "countries".* FROM "countries" WHERE "countries"."name" = $1  ORDER BY "countries"."id" ASC LIMIT 1  [["name", "Polska"]]
  Institution Load (0.3ms)  SELECT  "institutions".* FROM "institutions" WHERE "institutions"."country_id" = $1 AND "institutions"."name" = $2  ORDER BY "institutions"."id" ASC LIMIT 1  [["country_id", 1], ["name", "Uniwersytet Jagielloński"]]
  Department Load (0.2ms)  SELECT  "departments".* FROM "departments" WHERE "departments"."institution_id" = $1 AND "departments"."name" = $2  ORDER BY "departments"."id" ASC LIMIT 1  [["institution_id", 1], ["name", "Wydział Filozoficzny"]]
   (0.1ms)  BEGIN
  Affiliation Exists (0.3ms)  SELECT  1 AS one FROM "affiliations" WHERE ("affiliations"."person_id" = 17 AND "affiliations"."department_id" = 4) LIMIT 1
  SQL (0.8ms)  INSERT INTO "affiliations" ("department_id", "person_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["department_id", 4], ["person_id", 17], ["created_at", "2016-03-03 09:42:12.328380"], ["updated_at", "2016-03-03 09:42:12.328380"]]
   (17.6ms)  COMMIT
Redirected to http://localhost:3000/people/17
Completed 302 Found in 61ms (ActiveRecord: 20.3ms)
```

**Comment by apohllo** [comment]
Faktycznie jest problem - zaraz wyślę poprawkę.

**Comment by hryniawska** [comment]
Działa już - dodałam w bazie danych Country, Institution i Department i wtedy można już wybrać z autoselecta te propozycje - i ładnie się dodaje

**Comment by apohllo** [comment]
Poprawki są już w drodze

**Comment by hryniawska** [comment]
Czyli jednak ma to tak nie działać? Po dodaniu do bazy ładnie śmiga

**Comment by apohllo** [comment]
:] Tzn. powinno działać, ale nie działa - testowałem na istniejących instutucjach i "u mnie działało". Ale jak przetestowałem na nieistniejących instytucjach, to nie działało :-) Za chwilę kod będzie na masterze.

**Comment by apohllo** [comment]
Można zrobić `git pull apohllo master`

**Comment by hryniawska** [comment]
Dziękujęę!! Już siadam do testów :)
