### ISSUE TITLE
Dodanie statusów do artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#129]
Statusy te powinny być następujące:
- korekta redakcyjna
- korekta autorska
- opublikowany

Powinny być oznaczone różnymi kolorami.

**Comment by ghost** [comment]
zajmuję

**Comment by apohllo** [comment]
To zadanie zostanie nieco zmodyfikowane. O szczegółach porozmawiamy na konsultacjach.

**Comment by ghost** [comment]
Zależy od #55 Status powinien być przypisany do artykułu a nie zgłoszenia.

**Comment by ghost** [comment]
Czy te statusy dotyczą artykułów w issues czy w public_issues?

**Comment by apohllo** [comment]
Tylko w issues.

**Comment by apohllo** [comment]
Tzn. żebyśmy się źle nie zrozumieli - mają być wyświetlane w issues i tam też modyfikowane. Przynależą one do klasy `Article`, która wykorzystywana jest zarówno w kontrolerze `issues` jak i w `public_issues`.
