### ISSUE TITLE
Streszczenie i słowa kluczowe tylko w j. angielskim

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#13]
Streszczenie i słowa kluczowe w widoku edycji zgłoszenia powinny być tylko w j. angielskim. 
Tytuł, streszczenie i sł. kluczowe w j. angielski powinny być wymagane. Tytuł w j. polskim powinien być wymagany tylko jeśli artykuł jest w j. polskim.

**Comment by drianka** [comment]
zgłaszam się
