### ISSUE TITLE
Generowanie metryk tekstów w j. angielskim

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#132]
System powinien generować zbiorczy widok HTML, który, dla artykułów przyjętych do
druku powinien zawierać:
- ich angielski tytuł 
- ich angielskie streszczenie
- ich angielskie słowa kluczowe

Funkcja zależy od implementacji #2

**Comment by kosowina** [comment]
spróbuję

**Comment by apohllo** [comment]
Proszę to zrobić na bazie np. https://github.com/apohllo/rocznik/pull/296/files
Tzn. mamy konkretny numer rocznika i po kliknięciu guzika widzimy metryki wszystkich artykułów w j. angielskim.

**Comment by apohllo** [comment]
Zrobione w ramach #471
