### ISSUE TITLE
Zmiany w formularzu zgłoszeniowym

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#14]
Formularz zgłoszenia nowego artykuły powinien:
- zawierać widget wyboru daty zgłoszenia
- mieć pola "finansowanie" oraz "uwagi edytora" przesunięte na koniec

**Comment by hakuna18** [comment]
Zrobię!

**Comment by hakuna18** [comment]
Czy mógłby Pan podpowiedzieć, co powinnam zrobić? Bo wydaje mi się, że to zadanie zostało już wykonane...

**Comment by apohllo** [comment]
Proszę dodać opis dla poszczególnych pól - ale w widoku publiczym (`app/views/public_sumbssions`) - na wzór finansowania.
