### ISSUE TITLE
Filtorwanie artykułów po redaktorze

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#15]
Redaktor powinien mieć możliwość odfiltrowania zgłoszonych artykuł, tak by wyświetlały się tylko te, które są pod jego opieką. Ten wybór powinien być zapamiętany, niezależnie od dalszych działań w interfejsie użytkownika, tzn. przejście do widoku osób, a następnie zgłoszeń nadal powinno wyświetlać tylko redagowane artykuły.

**Comment by olkaf123** [comment]
biorę

**Comment by olkaf123** [comment]
mam mały problem z c9.io (błąd ip i portu) - chciałabym przyjść do Pana na konsultacje. jest Pan na uczelni dopiero w czwartek od 14, czy byłaby szansa, żeby przyjść jakoś wcześniej?
