### ISSUE TITLE
Opracowanie szaty graficznej czasopisma

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#150]
Poza opracowaniem układu strony oraz architektury informacji (które ujęte są w innych zgłoszeniach) przydałoby się ożywić nieco stronę internetową poprzez opracowanie ciekawszej szaty graficznej. Zadanie obejmuje przygotowanie 2 koncepcji kolorystyczno-graficzych oraz wdrożenie jednej z nich ich w aplikacji.

**Comment by dzikichomik** [comment]
Zgłaszam się do wykonania zadania.
