### ISSUE TITLE
Dodanie nowego konta w trakcie dodawania zgłoszenia

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#152]
W mejlu wysyłanym do autora, który nie był wcześniej zarejestrowany w systemie powinno pojawić się hasło do nowoutworzonego konta. Konto to powinno powstać w następstwie zgłoszenia artykułu do recenzji. Implementacja zależy od #151

**Comment by roksana1** [comment]
spróbuje

**Comment by roksana1** [comment]
Nie końca wiem, jak zabrać się za to zadanie.. Czy w ogóle mogę zacząć, jeśli #151 jest nieskończone?
Jeśli dobrze rozumiem, to do #151 powinnam dodać warunek sprawdzający istnienie autora w bazie i w razie, gdy nie ma jeszcze konta, to do mejla powinna zostać dopisana informacja o nowoutworzonym koncie i tymczasowe passy do niego oraz funkcja, która doda nowego użytkownika do bazy?
Pozdrawiam.
