### ISSUE TITLE
Zaimplementować widok stanu zgłoszonych artykułów dla autora

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#153]
Autor po zalogowaniu powinien mieć wyświetlaną listę zgłoszonych artykułów (artykułów, w których jest autorem korespondującym) wraz z ich statusem. Lista ta powinna również zawierać informację o liczbie przypisanych recenzentów, którzy zaakceptowali przygotowanie recenzji.

**Comment by Clodia** [comment]
zajmuję

**Comment by Clodia** [comment]
Wspominał Pan, ze mogę zrobić to zadanie na podstawie któregoś kontrolera, ale nie widzę niczego podobnego? Czy ma Pan jakieś preferencje co do nazwy tego kontrolera i w którym miejscu chciałby Pan, by wyświetlała się ta lista, w której zakładce, dostępna tylko dla autora, czy na stronie głównej dla autora po zalogowaniu? 

Jakieś inne wskazówki co do tego zadania?

Z góry dziękuję za pomoc.

**Comment by apohllo** [comment]
To już chyba sobie wyjaśniliśmy? Bo nie pamiętam.

**Comment by Clodia** [comment]
Raczej tak

**Comment by Clodia** [comment]
1. Zrobiłam wpis w rails_helper, nie wiem tylko, czy poprawny?
2. Czy dobrze, że testy umieściłam w osobnym pliku? Czy może lepiej zrobić je jakoś w submissions_spec?
3. Co z testami, jak nie działają?
