### ISSUE TITLE
Wysyłanie prośby o recenzję do recenzenta

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#154]
Dla recenzenta przypisanego do recenzji powinien istnieć przycisk w widoku zgłoszenia, za pomocą którego do recenzenta wysyłane jest zapytanie o możliwość sporządzenia recenzji.
Adresem zwrotnym wiadomości powinien być adres redaktora prowadzącego.

**Comment by Anaasz** [comment]
Rezerwuję

**Comment by patrykolczyk** [comment]
to jak będzie odbywać się akceptacja lub odrzucenie artykułu do recenzji? Moje zadanie jest związane z tym zadanie i zupełnie nie wiem jak to ugryźć. 
chodzi mi o #195 oraz #188

**Comment by Anaasz** [comment]
@patrykolczyk W zasadzie zadanie 155 jest już prawie gotowe. Mam tylko problem z linkiem w mailu. Poza linkiem raczej już nic nie będzie zmieniane. Po kliknięciu w link powinno nastąpić przekierowanie do review.submission (zobacz plik app/controllers/reviews_controller.rb w moich commitach). Pewnie tam będziesz musiał przekierować do swojego widoku :)

**Comment by patrykolczyk** [comment]
@apohllo a czy widział Pan moją propozycję grafiki ?
