### ISSUE TITLE
Pobieranie artykułu przez recenzenta

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#158]
Zależy od #155 
Po kliknięciu odnośnika z #155 recenzent powinien być kierowany na stronę na której może pobrać artykuł. Na stronie tej powinno również pojawić się pole z proponowanym terminem sporządzenia recenzji ustawionym na 1 miesiąc "do przodu".

**Comment by roksana1** [comment]
zajmuje

**Comment by roksana1** [comment]
W którym kontrolerze powinnam dodać widok strony z artykułem? reviews_controller?

**Comment by apohllo** [comment]
Dodać akcję w public_submissions - `download`, która będzie zwracać ten dokument.

**Comment by apohllo** [comment]
Jednak lepiej w `public_reviews`.
