### ISSUE TITLE
Dodać sekcję "Publikowane artykuły" w widoku pojednyczego numeru

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#184]
W widoku pojedynczego numeru rocznika w panelu administracyjnym dodać sekcję (pod istniejącą sekcją "Zgłoszone artykuły") "Publikowane artykuły". W tej sekcji powinny się pojawić artykuły powstałe w wyniku implementacji #176 tzn. artykuły przygotowywane do publikacji w ramach tego numeru.

**Comment by olabas** [comment]
zgłaszam się :)
