### ISSUE TITLE
Uniemożliwić usuwanie artykułu, do którego przypisane są recenzje

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#185]
Jeśli do artykułu przypisana jest choć jedna recenzja, to nie może on zostać usunięty. W celu usunięcia takiego artykułu konieczne jest najpierw usunięcie wszystkich recenzji. Ma to na celu zabezpieczenie przed sytuacją, w której redaktor omyłkowo usunie artykuł, który jest już w recenzji. W trakcie próby usunięcia takiego artykułu redaktor powinien otrzymać informację, że najpierw trzeba usunąć recenzje.

**Comment by Xerlith** [comment]
Biorę.

**Comment by Xerlith** [comment]
http://guides.rubyonrails.org/association_basics.html
