### ISSUE TITLE
Dodać widok/grafikę, gdy recenzent zgodzi się recenzować artykuł.

### ISSUE THREAD

**Issue by patrykolczyk** [apohllo/rocznik#195]

**Comment by patrykolczyk** [comment]
ja

**Comment by patrykolczyk** [comment]
Czy coś w ten deseń? Oczywiście będzie to jeszcze pokolorowane.
Aby zachować spójność, to po odrzuceniu garfika będzie ta sama z tym, że mina pana będzie smutna a zamiast braw - kciuki w dół .
Czy powinienem pójść w zupełnie inną - nie tak ilustracyjną formę?
![po akceptacji - szkic](https://cloud.githubusercontent.com/assets/7061584/13196394/5aed55e0-d7cc-11e5-8179-8850112ec34f.jpg)

**Comment by patrykolczyk** [comment]
@apohllo czy moglby mi Pan dać jakiś feedback?

**Comment by apohllo** [comment]
Może bez kciuków w dół

**Comment by apohllo** [comment]
BTW - można by zrobić dwie wersje - męską i żeńską - wtedy byłyby za 2 punkty

**Comment by patrykolczyk** [comment]
![koles na igaa](https://cloud.githubusercontent.com/assets/7061584/13407783/77e6da4e-df2a-11e5-8d3f-5c0114900197.jpg)

**Comment by patrykolczyk** [comment]
oraz kobieta :) @apohllo co Pan sądzi? dobrze?

![babka na igaa](https://cloud.githubusercontent.com/assets/7061584/13527199/a2dd09b8-e20d-11e5-892d-60661718cd42.jpg)

**Comment by apohllo** [comment]
jest super
