### ISSUE TITLE
Przypisanie zgłoszeń do numerów rocznika

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#2]
Dodać możliwość przypisywania zgłoszonych artykułów do konkretnych numerów rocznika oraz filtrowania recenzji oraz zgłoszeń ze względu na numer.

**Comment by apohllo** [comment]
Artykuły pojawiają się w kolejnych numerach Rocznika Kognitywistycznego. Aktualnie wszystkie zgłoszenia trzymane są w jednym "worku", co np. uniemożliwia odfiltrowanie zgłoszeń, które już zostały w przeszłości zrecenzowane i zostały opublikowane albo odrzucone. Dodanie modelu `Issue`, który opisywałby konkretne wydanie Rocznika oraz powiązanie go ze zgłoszeniami pozwoli na zawężenie widoku zgłoszeń do wybranego wydania.

**Comment by korzy** [comment]
Zgłaszam się do tego zadania.

**Comment by apohllo** [comment]
Implementacja powinna wyglądać następująco:
- model `Issue` powinien mieć dwa pola typu integer: `year` oraz `volume`
- model `Submission` powinien należeć do jednego `Issue` a jedno `Issue` powinno mieć wiele `Submission`
- powinien istnieć scaffold dla `Issue` analogiczny jak dla pozostałych elementów modelu
- powinien istnieć link do `Issue` w menu głównym
- w formularzu edycji `Submission` powinna istnieć możliwość wyboru `Issue` (najlepiej od najnowszego)
