### ISSUE TITLE
Formularz zgłoszenia artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#22]
Opracować kompletny formularz zgłoszenia artykuły dostępny dla niezarejestrowanych użytkowników.
Formularz ten powinien być dostępny bez logowania, ale tworzyć zgłoszenie zgodnie z modelem wykorzystywanym w panelu administratora. W szczególności dotyczy to zagadnień takich jak:
- zgłaszania wielu autorów, wraz z ich nazwiskami, adresami e-mail, afiliacjami, etc.
- tworzenie początkowej wersji artykułu

**Comment by ecolla** [comment]
zajmę się tym zadaniem

**Comment by apohllo** [comment]
Formularz ten powinien być zgodny z wymogami opisanymi w historii [Zgłaszanie artykułu do recenzji](/apohllo/rocznik/wiki/Zgłaszanie-artykułu-do-recenzji)

**Comment by ecolla** [comment]
``` ruby
  def new
    @submission = Submission.new
    @submission.status = 'nadesłany'
    @author_id = params[:author_id]
  end

  def create
    @submission = Submission.new(new_submission_params)
    @submission.received = Time.now
    @author_id = params[:author_id]
    if @submission.save
      if @author_id
        authorship = Authorship.new(person_id: @author_id,submission: @submission)
        authorship.save
      end
      redirect_to @submission
    else
      render :new
    end
  end
```

Dzień dobry, 
Czemu służy parametr :author_id? Skąd ma się wziąć w akcji new?
Jaki jest związek autora z użytkownikiem - czy osoba wysyłajca formularz jest także autorem czy też nie? W akcji create jest tworzony Authorship, natomiast z opisu zadania wynika, że autorów może być kilku - dlaczego?

**Comment by apohllo** [comment]
Przeniesione z Pull-requestu
- przenieść zmiany z `submissions_controller` do `public_submissions_controller`
- w pierwszym formularzy usunąć dane na temat autora, a dodać dane dotyczące wersji
- zrobić kolejny formularz, w którym będą dodawani autorzy, jeden "na raz"
  - na dole będą dwie możliwości: dodaj, zakończ
- na koniec wyświetlić podziękowanie za złożenie artykułu
- tworzymy autora, jeśli nie ma go w bazie - sprawdzamy przez e-mail czy nie ma już w bazie
- w formularzu autora musi być ukryte pole `submission_id`, które wskazuje zgłoszenie do którego dodawani są autorzy
- w formularzu autora, pamiętać o checkboksie `corresponding` (autor korespondujący)
- `position` ma być ustawiana automatycznie (podobnie jak `submission_id` musi być jak pole ukryte)
- w zgłoszeniu akceptować dane dla `ArticleRevision` (wprowadzenie l. stron itp.)
- w `ArticleUploader` dodać `pdf`
- link `Dodaj artykuł` przenieś na lewą stronę w layoucie
- wyrzucić migrację `add_article_to_submission`, czyli właściwie dodać migrację odwrotną
- dodać odpowiednie ścieżki w pliku `routes.rb`
