### ISSUE TITLE
Formularz zgłoszenia recenzji

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#24]
W systemie powinien być formularz recenzji artykułu, który powinien być dostępny dla niezalogowanych użytkowników. Dostęp do formularza powinien odbywać się na podstawie linku zawierającego losowo wygenerowaną kombinację liter i cyfr oraz podania adresu e-mail w celu weryfikacji. Formularz ten powinien odpowiadać danym wprowadzanym dla recenzji w panelu administracyjnym. W panelu administracyjnym powinna istnieć możliwość odwiedzenia tego odnośnika.
Dodanie recenzji powinno skutkować zmianą jej statusu.

**Comment by rosablomma** [comment]
zajmę się tym zadaniem
