### ISSUE TITLE
Filtrowanie zgłoszeń po tytule

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#244]
W widoku zgłoszeń powinna istnieć możliwość filtrowania ich po tytule. Powinno to działać analogicznie jak filtrowanie osób po nazwisku.

**Comment by paula-** [comment]
Zgłaszam się

**Comment by paula-** [comment]
Szanowny Panie Doktorze, 

zabrałam się do wykonania tego zadania, po czym zauważyłam, że filtrowanie zgłoszeń po tytule zostało już zaimplementowane przez kogoś innego. Prześledziłam zmiany plików na GitHubie i zobaczyłam, że potrzebne linijki pojawiły się w commitcie 9e4db328fce86190fa54e2d76a1c3de961ee4b36 (Drianka 285-1 w zadaniu 292, https://github.com/apohllo/rocznik/commit/9e4db328fce86190fa54e2d76a1c3de961ee4b36)

W folderze views/submissions, w pliku index.html.haml pojawiły się linijki odpowiedzialne za budowanie kryteriów filtrowania dla Ransacka : 

```
.scroll-panel-body
  = simple_search_form_for @query do |f|
    = f.input :status_start, collection: Submission::STATUS_MAPPING.keys, include_blank: true
 **   = f.input :english_title_or_polish_title_cont, label: "Tytuł"**
```

Oraz dodano test w spec/features/submissions_spec.rb:

```
scenario "Filtrowanie zgłoszeń po tytule" do
          visit "/submissions"

          fill_in "Tytuł", with: "Alicja w krainie czarów"
          click_on("Filtruj")

          expect(page).to have_content("Alicja w krainie czarów")
          expect(page).not_to have_content("W pustyni i w puszczy")
        end
```

Dlatego nie wysyłałam żadnego pull requesta, bo uznałam, że nie jest to już potrzebne.

Z wyrazami szacunku, 
Paulina Gurgul

**Comment by apohllo** [comment]
Ok, zatem proszę to samo zaimplementować w widoku publikowanych artykułów.
Jedyna różnica będzie polegała na tym, że zamiast:
`english_title_or_polish_tilte_cont` napisze Pani `submission_english_title_or_submission_polish_title_cont`. I test i będzie gotowe.
