### ISSUE TITLE
Filtrowanie recenzji po tytule

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#245]
W widoku recenzji powinna istnieć możliwość filtrowania ich po tytule. Powinno to działać analogicznie jak filtrowanie osób po nazwisku, z tym zastrzeżeniem, że tytuł przypisany jest do zgłoszenia a nie recenzji.

**Comment by paula-** [comment]
Zgłaszam się

**Comment by paula-** [comment]
Szanowny Panie Doktorze, 

Pull request z wykonanym zadaniem filtrowania recenzji po tytule znajduje się pod linkiem: https://github.com/apohllo/rocznik/pull/380
