### ISSUE TITLE
Zmiana formularzy Devise tak by korzystały z bootstrapa

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#250]
Aktualnie formularze do logowania odstają od pozostałych formularzy, ponieważ nie korzystają z Bootstrapa. Zadanie polega na tym żeby zmodyfikować je tak, by korzystały z bootstrapa.
Można to zrobić za pomocą polecenia:

```
rails g devise:views:i18n_templates
```

Należy się upewnić, że komunikaty wyświetlają się po polsku oraz, że nowy formularz rejestracji pozostaje bez zmian #47 

Warto przeczytać https://github.com/plataformatec/simple_form/wiki/Simple-Form-with-Devise

**Comment by zuravska** [comment]
spróbuje to zrobić dzis lub jutro bo nie moge zrobic innych swoich zadań zależnych od innych

**Comment by zuravska** [comment]
czyli to jest juz zamkniete?
