### ISSUE TITLE
Generowanie listy recenzentów

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#26]
Po wybraniu konkretnego wydania #2 powinna istnieć możliwość wygenerowania listy recenzentów, uczestniczących w recenzowaniu artykułów. Lista ta powinna być generowana wyłącznie wtedy gdy statusy wszystkich artykułów określone są jako zaakceptowany/odrzucony i powinna obejmować:
- recenzentów przyjętych artykułów
- recenzentów odrzuconych artykułów

Lista ta nie powinna obejmować recenzentów, którzy nie przyjęli artykułu do recenzji.

Lista powinna być generowana w postaci widoku html.

**Comment by korzy** [comment]
Zgłaszam się do tego zadania.

**Comment by korzy** [comment]
Przekazuję to zadanie użytkownikowi mbasik

**Comment by apohllo** [comment]
@mbasik  Czy  Pani potwierdza?

**Comment by mbasik** [comment]
Tak, w zamian oddaję zadanie numer #29 korzy.
