### ISSUE TITLE
Opracowanie i zaimplementowanie widoku listy numerów w części publicznej

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#266]
Chodzi o widok, który pojawia się po kliknięciu "Numery" w menu po lewej stronie. Widok ten powinien być bardziej atrakcyjny dla użytkownika.

**Comment by olabas** [comment]
spróbuję, jak nie zacznę tego dzisiaj to zwolnię komuś innemu ;)

**Comment by olabas** [comment]
W jaki sposób mogę zmienić ten widok? Gdzie znajdują się pliki z css'ami, bo nie potrafię tego znaleźć, a w samym szkielecie index.html.haml chyba nie da się tego zrobić bardziej atrakcyjnym, prawda?

**Comment by olabas** [comment]
oddaje to zadanie dla lukikrk
