### ISSUE TITLE
Zmiana atrybutu title dla podstron

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#269]
Na podstronach tytuł strony (czyli atrybut `title`) powinien się zmieniać, np. jeśli wybierzemy w menu administratora `Numery rocznika` to tytuł powinien brzmieć `Numery rocznika - Rocznik Kognitywistyczny` dla wszystkich akcji wykonywanych w ramach tej sekcji.

Implementacja powinna wyglądać następująco - w kontrolerze powinien być dodany filtr 

``` ruby
  before_action :set_title

  #...
  private
  def set_title
    @site_title = 'Numery rocznika - '
  end
```

W layoucie zaś sekcja title powinna wyglądać następująco:

```
%title
  = @site_title
  Rocznik Kognitywistyczny
```

**Comment by Rudziszcze91** [comment]
Pierwszy plik do poprawy ma ścieżkę app/controllers/affiliations_controller.rb?

**Comment by apohllo** [comment]
Zmiany trzeba zrobić we wszystkich kontrolerach, tzn. wszystkich plikach w katalogu `app/controllers`

**Comment by kosowina** [comment]
pracuję na tym, ale nie wiem jak przeprowadzić testy.

**Comment by korowadlo** [comment]
mam zrobione (przynajmniej tak wygląda). tez bez testów... oh well trzeba znaleźć inny issue

**Comment by kosowina** [comment]
haha, nie no, bierz :)

**Comment by korowadlo** [comment]
Dziękować. :D
