### ISSUE TITLE
Nowy typ zgłoszenia - komentarz do tekstu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#277]
Do zgłoszenia powinien być dodany atrybut określający, czy tekst jest oryginalnym artykułem naukowym, czy komentarzem do innego, opublikowanego artykułu. W modelu powinno zostać dodane powiązanie pomiędzy zgłoszeniami i artykułami, wskazujące, że dany komentarz (zgłoszenie) jest przynależy do danego, opublikowanego artykułu.

**Comment by olabas** [comment]
spróbuję
