### ISSUE TITLE
Obliczenia liczby recenzetów spoza UJ

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#28]
System powinien generować dla wybranego numeru #2 informację o liczbie oraz udziale procentowym recenzentów z UJ oraz spoza UJ. Przy obliczaniu powinny być uwzględnione te same założenia co w przypadku #26

**Comment by korzy** [comment]
Zgłaszam się do tego zadania.

**Comment by Grzesiek94** [comment]
@korzy odstąpił to zadanie, biorę ;)

**Comment by korzy** [comment]
Potwierdzam
