### ISSUE TITLE
Obliczanie liczby recenzentów z zagranicy

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#29]
Dla wybranego numeru #2 system powinien obliczać liczbę oraz udział procentowy recenzentów z zagranicznych ośrodków. Przy ich obliczaniu obowiązują te same ograniczenia jak w przypadku #26.

**Comment by mbasik** [comment]
Chciałabym to zrealizować.

**Comment by korzy** [comment]
Przejmuję to zadanie w zamian za #26 dla mbasik

**Comment by Grzesiek94** [comment]
@korzy odstąpił to zadanie, biorę ;)

**Comment by korzy** [comment]
Potwierdzam
