### ISSUE TITLE
Wysyłanie decyzji do autora korespondującego

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#35]
Po zaakceptowaniu statusu zgłoszenia:
- zaakceptowane
- odrzucone
- do poprawy (istotnej lub drobnej)

(patrz #37)

powinna istnieć możliwość wysłania gotowej odpowiedzi do autora korespondującego informującego o decyzji. Wiadomość ta powinna zawierać pełne recenzje pracy, bez podawania autorów recenzji.

**Comment by dzikichomik** [comment]
Zgłaszam się do wykonania zadania.

**Comment by lukikrk** [comment]
Zaklepuję!
