### ISSUE TITLE
Usunięcie pól w recenzji związanych z kryteriami oceny

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#37]
W formularzu recenzji usunięte powinny być wszystkie pola w dziale ocena. 
Dodatkowo status "do poprawy" powinien być rozbity na dwa: "niewielka poprawa" "istotna poprawa"

**Comment by martasiedlecka** [comment]
Ja bym dała inne pola, zgodne ze standardami zagranicznych czasopism (w stronę których powinniśmy chyba zmierzać):
- akceptacja
- minor review (akceptacja po drobnych poprawkach i uzupełnieniach, Edytor moze juz sam podjąć decyzję)
- major review (poważna poprawa tekstu, a po niej kolejna recenzja)
- odrzucenie
  Oczywiście do dyskusji jest polska terminologia :)

**Comment by apohllo** [comment]
OK. Zatem to zadanie powinno definiować cztery możliwości wymienione wyżej. Zmieniłbym tylko nazewnictwo:
- minor review -> niewielkie poprawki
- major review -> istotne poprawki (wymagają powtórnej recenzji)

**Comment by martasiedlecka** [comment]
super

**Comment by anbo222** [comment]
Zgłaszam się do tego zdania

**Comment by anbo222** [comment]
"Formularz recenzji" chodzi o edytowanie recenzji czy jakiś inny widok?
A jeśli o edytowanie - to pola w dziale ocena są następujące :
Ocena ogólna
Zgodność z tematyką
Poprawność merytoryczna
Język
Zrozumiałość
Literatura
Oryginalność
Treść recenzji
Wszystkie je usunąć?
Bo z kolei Status, który jest wyżej (Dział edycji) ma opcję ustalenia akceptacji.
Co powinno pozostać, a co jest do usunięcia?

**Comment by apohllo** [comment]
Usunąć:
- Ocena ogólna
- Zgodność z tematyką
- Poprawność merytoryczna
- Język
- Zrozumiałość
- Literatura
- Oryginalność

**Comment by apohllo** [comment]
Zadanie to wymaga również wyboru odpowiednich reprezentacji kolorystycznych dla nowych statusów (mogą to być różne odcienie pomarańczowego).

**Comment by anbo222** [comment]
Czy po usunięciu pól w sekcji ocena nazwa sekcji nie powinna się zmienić? (pozostało tam tylko pole Treść recenzji)

**Comment by apohllo** [comment]
Tak, warto byłoby:
- usunąć header Ocena
- przesunąć pole "treść recenzji" przed "uwagi"
- powiększyć pole "treść recenzji" (3 krotnie)

**Comment by apohllo** [comment]
Również w widoku recenzji należy usnąć tę sekcję.
Należy również usunąć pola w bazie danych.
