### ISSUE TITLE
Sortowanie zgłoszeń względem daty zgłoszenia

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#40]
Powinna istnieć możliwość sortowania zgłoszeń względem daty zgłoszenia. Przewiduje się zarówno sortowanie od najnowszego jak i od najstarszego.

**Comment by sylviacapella** [comment]
zgłaszam się

**Comment by sylviacapella** [comment]
Moduł Ransack https://github.com/activerecord-hackery/ransack - poczytać o sortowaniu
