### ISSUE TITLE
Wyświetlanie pełnego tytułu w widoku zgłoszenia

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#43]
W widoku zgłoszenia powinien wyświetlać się pełny tutuł.

**Comment by MarcinKulawik94** [comment]
To zadanie jest takie samo, jak #41, więc tutaj również napiszę, że rezerwuję, żeby później nie było nieporozumień, że dwie osoby się zgłosiły do tego samego zadania.

**Comment by apohllo** [comment]
Faktycznie to duplikat.
