### ISSUE TITLE
Dokowanie nagłówków tabeli w widokach listy

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#45]
Przy przesuwaniu listy osób, artykułów, recenzji, nagłówek tabeli powinien "dokować" się na górze. Tzn. być cały czas widoczny.

**Comment by MagdalenG** [comment]
Zajmę się tym !

**Comment by MagdalenG** [comment]
Oddaje to zadanie na konto Medz333

**Comment by apohllo** [comment]
Pozostawione bez rozwiązania.
