### ISSUE TITLE
Formularz zgłoszenia nowej wersji artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#46]
W systemie powinna istnieć możliwość dodawania nowej wersji artykułu przez autora korespondującego.

**Comment by martasiedlecka** [comment]
Bardzo ważna jest też możliwość dodawania odpowiedzi na recenzje.

**Comment by apohllo** [comment]
Funkcjonalność ta powinna być widoczna w głównym layoucie aplikacji a nie w panelu administratora.

**Comment by JoannaBy** [comment]
Zajmę się tym zadaniem.
