### ISSUE TITLE
Nowy formularz rejestracji pozwalający na podanie danych osobowych

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#47]
Formularz rejestracyjny powinien pozwolić na wprowadzenie następujących danych:
- e-mail
- hasło
- powtórz hasło
- stopień
- imię
- nazwisko
- płeć
- dziedzina wiedzy

Osoba, która zarejestruje się w systemie powinna mieć domyślnie przypisany status, co powinno umożliwiać jej zgłaszanie artykułów.

**Comment by mbasik** [comment]
Chciałabym to zadanie zrealizować.

**Comment by mbasik** [comment]
Niestety nie mogę dodać pull request na githubie, a po wykonaniu git pull apohllo master pojawia się error: Your local changes to the following files would be overwritten by merge: db/schema.rb, chociaż pobierałam nowe zmiany. Jakie jest rozwiązanie tego konfliktu?

**Comment by apohllo** [comment]
Proszę najpierw zacommitować (`git add db/schema.rb` potem `git commit`) a potem zrobić `git pull apohllo master`

**Comment by mbasik** [comment]
fatal: pathspec 'db/schema.rb' did not match any files

**Comment by apohllo** [comment]
W którym katalogu wywołuje Pani to polecenie?

**Comment by apohllo** [comment]
Proszę też wkleić wynik `git ls-files`

**Comment by mbasik** [comment]
Polecenie wywołuję w folderze registrations, czyli w miejscu, w którym pracuję nad kodem. W folderze tym są następujące pliki: edit.html.haml i new.html.haml.

**Comment by apohllo** [comment]
Trzeba je wywołać w głównym katalogu.
