### ISSUE TITLE
Mejl dla redaktora jeśli pojawi się nowa wersja artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#48]
Przy załadowaniu przez autora nowej wersji artykuły powinien być wysyłany mejl do recenzenta informujący o tym fakcie. Funkcjonalność ta zależy od implementacji funkcjonalności pozwalającej na dodawanie nowych wersji #46

**Comment by martasiedlecka** [comment]
Moim zdaniem tylko redaktor powinien dostawać mail, zdecydować, czy chce tekst poddawać recenzji ponownie.

**Comment by apohllo** [comment]
Faktycznie, chodziło mi o automatyczne wysłanie mejla do redaktora, a nie recenzenta.

**Comment by JoannaBy** [comment]
Zajmę się tym zadaniem.
