### ISSUE TITLE
Wyświetlanie recenzji w widoku zgłoszenia

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#5]
Zamiast przechodzić do edycji recenzji z widoku zgłoszenia, lepiej byłoby wyświetlać jej treść. Alternatywnie mogą być dwie ikonki - jedna do wyświetlenia, jedna do edycji (ta ostatnia tylko dla redaktora danego zgłoszenia).

**Comment by apohllo** [comment]
Aktualnie w widoku zgłoszenia, kliknięcie na statusie recenzji powoduje przejście do formularza edycji recenzji. Zamiast tego powinien pojawić się widok wyświetlający treść recenzji, w który powinien pojawić się guzik pozwalający na edycję recenzji.

**Comment by mzet94** [comment]
Rezerwuję.

**Comment by mzet94** [comment]
Czy to zadanie jest jeszcze aktualne? Jeżeli dobrze patrze, wygląda jakby ktoś juz to poprawił.

**Comment by anbo222** [comment]
Ja poprawiłam - dodałam wyświetlanie treści, bo tego wymagało moje zadanie #37

**Comment by mzet94** [comment]
Tak myślałam, że to Ty :P. Szkoda :(

**Comment by apohllo** [comment]
To zróbmy tak jak w opisie - tzn. proszę o dodanie ikonki, która pozwoli zmodyfikować recenzję. Najlepiej żeby była to jedna z ikno udostępnianych w Bootstrapie.

**Comment by mzet94** [comment]
Ustaliliśmy:
- w widoku listy recenzji dodać ikonkę "edytuj"
- w widoku pojedynczego zgłoszenia dodać ikonkę "edytuj" przy recenzji oraz ikonkę "wyświetl"
- aktualny link na statusie recenzji powinien być usunięty
