### ISSUE TITLE
Publikowanie numeru

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#55]
Po etapie redakcji zaakceptowanych artykułów (która odbywa się poza systemem) powinna istnieć możliwość opublikowania numeru. Opublikowanie powinno skutkować pojawieniem się danego numeru w publicznej części systemu i skutkować odpowiednimi zmianami w menu aplikacji.
Ta funkcjonalność zakłada wyświetlenie listy opublikowanych artykułów, uwzględniając:
- autorów
- tytuł artykułu

Implementacja tej funkcjonalności zależy od #2

**Comment by kraputa** [comment]
zgłaszam się do tego zadania
