### ISSUE TITLE
Indywiduwalne strony dla opublikowanych artykułów

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#56]
Po publikacji numeru #55 tytuły artykułów powinny być linkami do indywidualnych stron artykułów.
Na indywidualnej stronie artykułu powinny być wyświetlone następujące informacje:
- tytuł artykułu
- nazwiska autorów
- ich afiliacje
- streszczenie artykułu
- słowa kluczowe
- strony
- link do ściągnięcia artykułu

Indywidualne artykuły muszą być reprezentowane przez odrębną klasę _Article_, której zawartość jest inicjowana na podstawie informacji w klasie _Submission_. Posiada ona jednak dodatkowe informacje, tzn. strony oraz link do ściągnięcia, które nie są znane w momencie tworzenia Submission.
Zadanie to obejmuje zatem również utworzenie odpowiedniej pozycji w menu administracyjny, w którym można uzupełnić informacje o opublikowanych artykułach.

**Comment by dmitrijbes** [comment]
I will do this.

**Comment by apohllo** [comment]
Proszę zwrócić uwagę, że zadanie to zależy od innego - #55 który z kolei zależy od #2 Nie można będzie przystąpić do jego realizacji przed ukończeniem tamtych dwóch zadań.

**Comment by dmitrijbes** [comment]
I will wait until somebody done it, and if nobody is interested in theme, i will do  #55 and #2 too.

**Comment by apohllo** [comment]
Drobna meta-uwaga - przyjmijmy, że językiem komunikacji będzie polski :) Zadania są już opisane po polsku, więc angielski wprowadza pewną niespójność i może utrudnić porozumienie.

**Comment by dmitrijbes** [comment]
Oczywiście, ma Pan racje, ale myślalem, że właśnie poziom mojego polskiego będzie sprawiał klopot. Od teraz będę pisał po polsku.

**Comment by apohllo** [comment]
Myślę, że radzi sobie Pan bardzo dobrze :)
