### ISSUE TITLE
Dodanie informacji o podpisaniu umowy

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#59]
W systemie powinna być dodana informacja nt. autorów, których artykuły zostały przyjęte do publikacji, czy otrzymali do podpisu umowę wydawniczą.

**Comment by MagdalenG** [comment]
zajmę się tym !

**Comment by MagdalenaG** [comment]
@apohllo Osoba, jaka pisała komentarz wcześniej to MagdalenG, ja jestem MagdalenaG. Proszę usuń mnie, ja sama nie mogę ;)

**Comment by apohllo** [comment]
Faktycznie, nie zauważyłem pomyłki.

**Comment by MagdalenG** [comment]
Oddaje to zadanie na konto Medz333

**Comment by Medz333** [comment]
Czy dobrze to rozumiem, powinnam zamieścić dodatkowy atrybut w Person, informujący o podpisaniu umowy wydawniczej? Czy powinnam zamieścić tą informację w innym miejscu? W jaki sposób?

**Comment by Medz333** [comment]
Dobrze to rozumiem?

**Comment by Medz333** [comment]
Juz wykonałam zadanie
