### ISSUE TITLE
Poprawić layout strony głównej

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#6]
Strona, na której wyświetla się opis czasopisma wyświetla się niepoprawnie (jest zbyt szeroka), co powoduje wyświetlenie belki do przesuwania. Layout powinien być tak poprawiony, aby na stronie głównej nie było poziomej belki (tzn. scrolla), ale również nie powinien zmienić się sposób wyświetlania tabelek w widoku administratora.

**Comment by julkapuk** [comment]
zrobie

**Comment by apohllo** [comment]
To zadanie jest b. proste. Czy mogłaby Pani poprawić to jak najszybciej? Tutaj nie chodzi o to, żeby jakoś pracować nad nowym layoutem, tylko, żeby nie wyświetlała się ta pozioma belka.

**Comment by julkapuk** [comment]
Czy mogłyby Pan mi napisać gdzie znajduje się widok dla treści strony głównej (opis czasopisma) ?

**Comment by apohllo** [comment]
app/views/layouts

**Comment by julkapuk** [comment]
Dziękuje, ale miałam na myśli sam opis, który jest na stronie głównej - charakterystyka czasopisma.

**Comment by apohllo** [comment]
edycja w górnej belce

**Comment by apohllo** [comment]
Chyba, że chodzi Pani o kod - to jest po stronie systemu Storytime:
https://github.com/CultivateLabs/storytime

**Comment by julkapuk** [comment]
Dlaczego po zmergowaniu nie pojawiły się moje zmiany w pliku app/views/layouts/application.html.haml?

**Comment by apohllo** [comment]
tldr; ma Pani łącznie zaliczone zadania z 5 punktów

Zrobiłem research dot. layout oraz menu.
- jeśli chodzi o poprawne wyświetlanie wiadomości to trzeba było "nadpisać" widok stortime - zrobiłem to w osobnym branchu, który sam zmergowałem
- jeśli chodzi o pojawianie się menu w widoku responsywnym - przeniosłem tę zmianę do application.js - dzięki temu można będzie aktualizować bootstrapa z poziomu railsów - bez ingerencji w plik layoutu

Czy ma Pani jeszcze jakieś pytania?

**Comment by julkapuk** [comment]
Nie, bardzo dziękuję za odpowiedź.
