### ISSUE TITLE
Dodawanie komentarzy do wersji artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#64]
W kontekście akceptacji ostatecznej wersji artykułu (patrz #63) istotne jest zebranie uwag od autorów.
Powinna zatem istnieć możliwość dodawania komentarzy do konkretnych wersji artykułu.
Istotne jest to, że w interfejsie musi istnieć możliwość zarówno dodania jak i wyświetlenia tych komentarzy dla konkretnej wersji artykułu (obecnie istnieje wyłącznie możliwość ściągnięcia konkretnej wersji). Funkcjonalność ta nie zależy jednak od #63 .

**Comment by MajaCh** [comment]
Zgłaszam się.

**Comment by MajaCh** [comment]
Chciałabym dookreślić kilka rzeczy związanych z zadaniem.
Nie widzę teraz w aplikacji nic odpowiedzialnego za komentarze - muszę stworzyć wszystko od zera - moje pytanie dotyczy tego jakie akcje miałyby być możliwe dla komentarzy. Wyświetlanie listy i tworzenie to oczywiste - ale czy po dodaniu ma być możliwość ich edytowania i usuwania samych komentarzy? Przy usuwaniu wersji artykułu powinny być usunięte też komentarze z nimi związane. Czy ma istnieć możliwość nawiązywania dyskusji - to znaczy czy można odpowiadać na konkretne komentarze czy po prostu dodawać je po kolei? 
W jaki sposób powinny się wyświetlać? Wstępnie widzę dwie możliwości - albo przy każdej dodanej wersji artykułu powinien się wyświetlać button rozwijający listę / przenoszący na stronę listy komentarzy albo na stronie zgłoszenia dodać sekcję komentarze podzielone na wersje. 
Czy gdzieś jeszcze powinien się wyświetlać guzik do sekcji komentarzy? Np. na profilu konkretnego użytkownika "Komentarze użytkownika"?

**Comment by apohllo** [comment]
Tutaj nie chodzi o komentarze w tym sensie, że można komentować artykuły. Chodzi tylko o, że przed zatwierdzeniem ostatecznej wersji artykułu przez autora, może on (ale nie musi) dodać komentarz co ma zostać poprawione przed publikacją (np. brak przecinka na 3 stronie). Dlatego komentarze te mają być atrybutem wersji artykułu. Powinna też istnieć możliwość edycji wersji artykułu, tak żeby możliwe było dodanie tego komentarza (oraz np. edycja liczby stron/ilustracji). To jest funkcjonalność dostępna tylko w panelu administratora. 

Co do wyświetlenia komentarzy dla pojedynczych artykułów to jeszcze nie mam do końca pomysłu. W sumie wystarczyłaby informacja czy komentarz jest czy nie (przy wersji artykułu). Na pewno potrzebne jest aby dla konkretnego numerów Rocznika można było zobaczyć wszystkie komentarze dodane przez autorów artykułów (dla każdego art. będzie co najwyżej 1 komentarz dot. poprawek). Żeby jednak zaimplementować tę funkcjonalność trzeba pobrać zmiany z `apohllo master` (tam są zdefiniowane już numery rocznika).

**Comment by MajaCh** [comment]
Po zrobieniu pulla i wywołaniu bundle wyrzuca błąd:

Sass::SyntaxError in Storytime::BlogHomepage#show

Showing /home/maja/Projekty/rocznik/app/views/shared/head.html.haml where line #17 raised:

File to import not found or unreadable: simple_form_autocomplete.
Load paths:
  /home/maja/Projekty/rocznik/app/assets/images
  /home/maja/Projekty/rocznik/app/assets/javascripts
  /home/maja/Projekty/rocznik/app/assets/stylesheets
  /home/maja/Projekty/rocznik/vendor/assets/javascripts
  /home/maja/Projekty/rocznik/vendor/assets/stylesheets
  /home/maja/.rvm/gems/ruby-2.2.3/gems/rails4-autocomplete-1.1.1/lib/assets/javascripts
  /home/maja/.rvm/gems/ruby-2.2.3/gems/storytime-2.0.0/app/assets/images
  /home/maja/.rvm/gems/ruby-2.2.3/gems/storytime-2.0.0/app/assets/javascripts
  /home/maja/.rvm/gems/ruby-2.2.3/gems/storytime-2.0.0/app/assets/stylesheets
  /home/maja/.rvm/gems/ruby-2.2.3/gems/storytime-2.0.0/vendor/assets/images
  /home/maja/.rvm/gems/ruby-2.2.3/gems/storytime-2.0.0/vendor/assets/javascripts
....

Extracted source (around line #4):

// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/
@import 'simple_form_autocomplete';              

// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/
@import 'simple_form_autocomplete';

Trace of template inclusion: app/views/layouts/application.html.haml

Rails.root: /home/maja/Projekty/rocznik
Application Trace | Framework Trace | Full Trace

app/assets/stylesheets/affiliations.scss:4
app/views/shared/head.html.haml:17:in `_app_views_shared_head_html_haml__897024153__641475438'
app/views/layouts/application.html.haml:3:in`_app_views_layouts_application_html_haml__507354414__645878578'

**Comment by apohllo** [comment]
Proszę wkleić zawartość `Gemfile.lock`

**Comment by apohllo** [comment]
Musi Pani przerwać działanie aplikacji (tam gdzie było wywołane rails s). Potem powinno już działać.
A jeśli nie, to proszę dać znać.
