### ISSUE TITLE
Dodać opis sekcji "finansowanie"

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#67]
Sekcja "Finansowanie" w opisie artykułu jest przeznacz do umieszczenia informacji kto finansował badani opublikowane w danym artykule.

Przy zgłaszaniu artykułu powinno pojawić się wyjaśnienie (np. w postaci tooltipa) o co chodzi w tej sekcji.

Przy wyświetlaniu artykułu #56 informacja ta również powinna pojawić się na stronie poświęconej artykułowi.

**Comment by olkaf123** [comment]
biorę

**Comment by Karolaa** [comment]
rezerwuję
