### ISSUE TITLE
Generator zaświadczenia o przyjęciu artykułu do druku

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#69]
W systemie powinna istnieć możliwość wygenerowania zaświadczenia w postaci dokumentu PDF, które informuje, że artykuł o określonym tytule, którego autorami są określone osoby, został przyjęty do druku w Roczniku XYZ. Implementacja zależy od #2 .

**Comment by kraputa** [comment]
Zgłaszam się do tego zadania.
