### ISSUE TITLE
Określenie kompetencji autorów i recenzentów

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#70]
Osoby zarejestrowane w systemie powinny mieć możliwość określenia swoich kompetencji. 
W systemie powinna istnieć możliwość wyszukiwania osób po kompetencjach (należy do tego wykorzystać funkcjonalność "full text search"). Funkcja wyszukiwania powinna być dostępna w widoku listy osób.

Kompetencje powinny być polem niezależnym od dyscyplin.

**Comment by drianka** [comment]
zgłaszam się

**Comment by drianka** [comment]
Czy kompetencjami są "Role", pojawiające się w formularzu tworzenia nowej osoby? Jeśli tak, to nie do końca wiem, co powinnam z tym zrobić. Albo źle rozumiem zadanie, albo częściowo zostało już zrobione ;)

**Comment by apohllo** [comment]
Nie, _role_ są tylko trzy (autor, recenzent, redaktor). W kompetencjach (które mają być po prostu polem tekstowym) chodzi o to, że można przypisać komuś _specjalizacje naukowe_, np. sztuczna inteligencja, psychologia percepcji, etc. Czyli jest to treść zupełnie innego typu. Natomiast _dyscypliny_ mogą mieć wartości takie jak filozofia, czy psychologia. Dlatego chcemy trzymać je w odrębnych polach.

**Comment by apohllo** [comment]
Do wyszukiwania należy użyć ransacka. Proszę przyjrzeć się temu jak wyszukiwane są osoby po nazwisku. Wystarczy dodać kolejne pole `:competence_cont`, które będzie wykorzystywane do wyszukiwania po kompetencjach. Powinien również istnieć test, weryfikujący działanie tego wyszukiwania.
