### ISSUE TITLE
Podanie listy proponowanych recenzentów przy zgłaszaniu artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#72]
W trakcie zgłaszania artykułu do recenzji autor powinien podać przynajmniej 3 recenzentów, co do których proponuje, aby byli recenzentami jego artykułu. Recenzenci powinni być wskazani z imienia, nazwiska oraz adresu e-mail. 

Jeśli w systemie już występują Ci recenzenci (weryfikacja na podstawie adresu e-mail), to zgłoszenie to jest automatycznie łączone z tymi recenzentami. Jeśli nie, to automatycznie tworzone są nowe rekordy odpowiadające tym recenzentom (ze wskazaniem roli "recenzent") i wiązane są one ze zgłoszeniem na tej samej zasadzie, na której obecnie wiązani są recenzenci z artykułami.

W systemie powinien istnieć nowy status recenzji "proponowana", który jest przypisywany do takiego zgłoszenia.

**Comment by MajaCh** [comment]
Zgłaszam się do zadania

**Comment by anbo222** [comment]
Zgłaszam się do tego zdania

**Comment by anbo222** [comment]
#22

**Comment by anbo222** [comment]
Czy zaczynać pracę w osobnym pliku (jeśli tak to jak go nazwać?), czy dołączyć to do pliku submission? I gdzie napisać selecta?

**Comment by apohllo** [comment]
Proszę utworzyć kontroler `AuthorSubmissionsController`, który będzie miał akcje `reviewers_form` oraz `reviewers`. Z tymi metodami ma być skojarzony widok `reviewers_form`, który wyświetla ten formularz. Akcja `reviewers` powinna dodawać do wybranego zgłoszenia proponowanych recenzentów. Wśród zgłoszeń powinny być tylko zgłoszenia danego autora (weryfikacja na podstawie e-maila). Jeśli zakończy się powodzeniem powinien wyświetlać się widok z podziękowaniem za przesłanie zgłoszenia. Zanim praca zostanie rozpoczęta proszę o przesłanie szkicu formularza (np. na kartce).
