### ISSUE TITLE
Podanie listy niechcianych recenzentów

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#73]
Funkcjonalność bazuje na implementacji #72 
W trakcie zgłaszania artykułu powinna również istnieć możliwość wskazania listy niechcianych recenzentów. Wtedy status tworzonej recenzji ustanawiany jest na "niechciana". 
W przypadku niechcianych recenzji konieczne jest podanie uzasadnienia dlaczego dana osoba jest "niechciana". Uwagi te powinny trafić do pola "Uwagi" występującego w recenzji.

**Comment by anbo222** [comment]
Zgłaszam się do tego zdania

**Comment by apohllo** [comment]
http://apidock.com/rails/ActionView/Helpers/FormOptionsHelper/options_for_select

**Comment by apohllo** [comment]
Dwie wartości:
- proponowany recenzent
- niechciany recenzent
