### ISSUE TITLE
Historia zmian stanu zgłoszenia

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#74]
W systemie powinna istnieć możliwość prześledzenia zmian stanu zgłoszonego artykułu.
Historia ta powinna uwzględniać datę, w której zmiana została dokonana oraz informację o tym,
kto dokonał zmiany.

**Comment by kraputa** [comment]
Zgłaszam się do tego zadania.

**Comment by patrykolczyk** [comment]
ja

**Comment by patrykolczyk** [comment]
czym mógłbym prosić o metode śedzenia tej zmiany? ma to być dodatkowa kolumna w tabeli?

**Comment by apohllo** [comment]
Nie da się tego zrobić w ten sposób. Musi być osobny model do śledzenia zmian statusu. Każde zgłoszenie będzie miało wskazanie na aktualny stan (wraz z datą modyfikacji) oraz na poprzedni. Ale w zasadzie nie powinno być  to trudne w realizacji, ponieważ istnieją gotowe biblioteki (np. paper trail), które ułatwiają realizację tego zadania.

**Comment by apohllo** [comment]
https://github.com/airblade/paper_trail

**Comment by patrykolczyk** [comment]
zwalniam
