### ISSUE TITLE
Status recenzenta

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#75]
Osoba, która jest recenzentem powinna mieć przypisane pole statusu, które może przyjmować jedną z wartości:
- nowy recenzent
- recenzuje w terminie
- recenzuje po terminie
- nie chce recenzować
- chce recenzować

Wybór statusu powinien być możliwy w oknie edycji osoby i być dostępny tylko dla osób, które mają status recenzenta.

**Comment by chibika** [comment]
Zgłaszam się

**Comment by apohllo** [comment]
Co trzeba zrobić?
- stworzyć migrację dodającą atrybut `status` do tabeli `people` typu `string
- trzeba zmodyfikować model i dodać w nim listę statusów oraz walidację
- trzeba zmodyfikować widok formularza edycji osoby
- trzeba dodać metodę `reviewer?` do klasy `Person`
- tej metody należy użyć w widoku do warunkowego wyświetlenia pola formularza

**Comment by apohllo** [comment]
- drugi warunek to to, że rekord nie jest nowy (`!@person.new_record?`)
