### ISSUE TITLE
Przekształcić pole "dyscyplina" w opisie osoby na związek

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#77]
Aktualnie w opisie osoby pole "dyscypliny" jest zrealizowane jako pole tekstowe.
Powinno ono zostać zamienione na związek wiele-do-wielu, tzn. jedna osoba może mieć przypisanych wiele dyscyplin. Należy zmodyfikować formularz edycji i wyświetlania osób, tak by odzwierciedlały tę zmianę. W systemie powinna również istnieć zakładka, w której administratorzy mogą określać listę dyscyplin. Dyscypliny powinny być określane w trakcie rejestrowania się nowych użytkowników.

**Comment by Rudziszcze91** [comment]
Wstępnie rezerwuję.
