### ISSUE TITLE
Dodać wyrażenie regularne weryfikujące tytuł/stopień naukowy osoby

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#78]
Dopuszczalne wartości:
- lic.
- inż.
- mgr
- mgr inż.
- dr
- dr inż.
- dr hab.
- dr hab. inż.
- prof. dr hab.
- prof. dr hab. inż.

**Comment by hryniawska** [comment]
zamawiam to zadanie

**Comment by hryniawska** [comment]
w jakim pliku powinnam dodać wyrażenie?

**Comment by hryniawska** [comment]
napisałam wyrażenie : 
(lic.|inż.|((mgr\s?(inż.)?)|((prof.\s?)?(dr\s?)(hab.\s?)?(inż.)?)))

w którym miejscu powinnam je wkleić?

**Comment by apohllo** [comment]
W pliku `app/models/person.rb` należy dodać odpowiedni walidator 
http://guides.rubyonrails.org/active_record_validations.html
