### ISSUE TITLE
Edycja hasła użytkownika

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#79]
W menu górnym powinien być link pozwalający na zmianę profilu użytkownika. 
W szczególności powinno być możliwe zmienienie:
- stopnia naukowego
- imienia i nazwiska
- hasła (co wymaga wcześniejszego powtórnego jego wprowadzenia)

System nie powinien umożliwiać zmiany adresu e-mail.

**Comment by mzet94** [comment]
Zamawiam.
