### ISSUE TITLE
Zmienić layout widoku administratora

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#8]
W widoku administratora tabelka wyświetlająca zgłoszenia, autorów, etc powinna zajmować całą szerokość (z uwzględnieniem marginesów, tak jak to ma miejsce w górnej belce). W menu powinien pojawić się link pozwalający na przejście do strony widocznej dla niezalogowanych użytkowników. Menu po lewej powinno być niewidoczne.

**Comment by ARaczka** [comment]
Zajmę się tym zadaniem.
