### ISSUE TITLE
Przygotowanie diagramu pokazującego przebieg procesu recenzji

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#80]
Zadanie polega na przygotowaniu schematu przedstawiającego proces recenzji (z punktu widzenia osoby nadsyłającej artykuł). Szczegóły do ustalenia w trakcie konsultacji.

**Comment by patrykolczyk** [comment]
ja

**Comment by patrykolczyk** [comment]
Zrobiłem taki diagram, wydaję mi się, że jest czytelny. Prosiłbym o uwagi :)
![diagram na ig](https://cloud.githubusercontent.com/assets/7061584/13407732/4258fe3e-df2a-11e5-8500-ae61d8610e8d.jpg)

**Comment by patrykolczyk** [comment]
![diagram na ig iii - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13410731/9631b942-df39-11e5-825b-86ac896d47f6.jpg)

**Comment by apohllo** [comment]
Trzeba będzie wprowadzić pewne poprawki, ale wygląda to nieźle. Czy będzie Pan jutro na konsultacjach?

**Comment by apohllo** [comment]
@dzikichomik Może Pani rzucić na to okiem?

**Comment by patrykolczyk** [comment]
TZN? Jakie poprawki? a o której odbędą się konsultacje??

**Comment by apohllo** [comment]
Np. nie są dla mnie jasne te czerwone linie które prowadzą do odrzucenia. Druga kwestia to np. fakt, że po pierwszej recenzji nie poszukuje się nowych recenzentów. itd. Nie ma jednak sensu tego wszystkiego opisywać, bo znacznie prościej będzie to wytłumaczyć "na żywo".

**Comment by apohllo** [comment]
Konsultacje są jutro od 12 do 14.45

**Comment by patrykolczyk** [comment]
![diagram na ig iv - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13421179/f4edf8e4-df8c-11e5-83f1-266c490e3289.jpg)

**Comment by patrykolczyk** [comment]
![diagram na ig v - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13421940/d7f6c18a-df91-11e5-8183-d8b2d73c4e99.jpg)

**Comment by patrykolczyk** [comment]
Zastosowałem poprawki, nowa wersja. 
Jak teraz @apohllo ?
![diagram na ig vi - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13469323/28851b4a-e0a7-11e5-8ef5-91be17141684.jpg)

**Comment by dzikichomik** [comment]
Jeśli o mnie chodzi - teraz diagram jest super czytelny i bardzo jasny i logiczny.
Uwagę miałabym tylko do kolorystyki - jeśli chciałabym go wrzucić na stronę główną (a taki jest zamysł), to na pewno tło musiałoby być białe (co automatycznie spowoduje dobór innego zielonego). Tutaj wzór z Bootstrapa: http://blackrockdigital.github.io/startbootstrap-agency/.
Zastrzeżenie interpunkcyjne, które mam - "Rocznik" jest czasopismem naukowym, akademickim, wystarczy sama "PUBLIKACJA" zamiast "! PUBLIKACJA !"; wykrzykniki nie mają uzasadnienia zarówno marketingowego, jak i interpunkcyjnego.

Ale tak czy siak - Patryk, dobry diagram, podoba mi się :-)

**Comment by apohllo** [comment]
No to jam ma zastrzeżenia :-) Te linie niebieskie nie wskazują w którym kierunku jest przepływ - dla mnie to nie jest logiczne - rozumiem to, bo wiem, o co chodzi, ale zwykły śmiertelnik może mieć problem z interpretacją. Skoro mamy boxy - to na początku również sensownie byłoby je połączyć linią ciągłą. Stan początkowy i końcowy mogłyby być wyróżnione w ten sam sposób (prostokąt - zmiana kontrastu). Generalnie jest lepiej, ale jeszcze trzeba to trochę dopracować - w szczególności po to, żeby było wiadomo co się dzieje przy poprawkach.

**Comment by apohllo** [comment]
Nadto, ponieważ `istotne poprawki` i `niewielkie poprawki` są decyzjami, to powinny być również wyróżnione jak pozostałe decyzje (`przyjęcie` i `odrzucenie`)

**Comment by apohllo** [comment]
Wydaje mi się również, że połączenie linii wychodzących z pierwszej recenzji byłoby celowe.

**Comment by apohllo** [comment]
Ale ogólnie to podoba mi się kierunek :-)

**Comment by patrykolczyk** [comment]
Nie chciałbym robić poprawek jako owale, to zaburzy juz, nie sa one postanowieniami ostatecznymi totez zostawiłbym je tak. zmieniłem kolorystyke i kierunki tez zaznaczyłem.
![diagram na ig vii - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13500788/52d5753a-e164-11e5-94bf-03f580c05d47.jpg)

**Comment by apohllo** [comment]
Prawie idealnie - chyba jednak dodałbym strzałkę pomiędzy `poszukiwaniem 2 recenzentów` a `niewielkimi poprawkami`.

**Comment by apohllo** [comment]
Bo teraz jest asymetria pomiędzy istotnymi poprawkami a niewielkimi poprawkami.

**Comment by patrykolczyk** [comment]
Proszę
![diagram na ig viii - poprawiona](https://cloud.githubusercontent.com/assets/7061584/13506300/cd1e8048-e17d-11e5-963f-2971072bf633.jpg)

**Comment by apohllo** [comment]
ok

**Comment by patrykolczyk** [comment]
Dziękuję :)
