### ISSUE TITLE
Wyszukiwanie informacji o recenzencie w Google

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#82]
W widoku recenzenta dodać link, który prowadzi do zapytania do Google na temat danej osoby.

**Comment by Karolaa** [comment]
Zajmę się tym zadaniem

**Comment by ghost** [comment]
Rezerwuję

**Comment by Clodia** [comment]
Rezerwuję

**Comment by apohllo** [comment]
Użytkownik @ghost był/była wcześniej.

**Comment by Clodia** [comment]
użytkownik @ghost nie istnieje, bo to byłam ja, ale usunęłam tamto konto :)

W dniu 8 grudnia 2015 15:20 użytkownik Aleksander Smywiński-Pohl <
notifications@github.com> napisał:

**Comment by apohllo** [comment]
No to prawdziwy @ghost ;-)
