### ISSUE TITLE
Numer DOI w opisie artykułu

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#84]
Każdy artykuł dostępny w publicznej części czasopisma musi posiadać numer DOI. Numer ten powinien prowadzić do "oficjalnej" strony artykułu.

**Comment by Karolaa** [comment]
Zajmę się tym zadaniem.

**Comment by apohllo** [comment]
Wyświetlanie poszczególnych artykułów jest realizowane przez @dmitrijbes Nie wiem na ile praca jest zaawansowana (nie ma pull-requestu). Dlatego zadanie to zrealizujemy nieco inaczej - dodam odpowiedni widok w panelu administracyjnym. Dam Pani znać jak będzie już dostępny.

**Comment by apohllo** [comment]
Widok jest już dostępny (Publikowane artykuły -> widok artykułu). Tam proszę dodać identyfikator DOI. Trzeba dodać odpowiednie pole w formularzu oraz wyświetlić w widoku artykułu. Przykład identyfikatora DOI dostępny jest pod adresem (na dole strony): http://www.ejournals.eu/Rocznik-Kognitywistyczny/2015/Rocznik-Kognitywistyczny-8-2015/art/5897/

Chcę aby w widoku pojawiał się odpowiedni odnośnik, ale sama treść odnośnika (to co widzi użytkownik) powinna być pozbawiona części dx.doi.org

**Comment by Karolaa** [comment]
Zgłoszenie może mieć jeden artykuł, i nie bardzo wiem jak zrobić dodawanie numeru doi do bazy... dodanie tego numeru musi być jak rozumiem już na poziomie tworzenia artykułu, czyli w /submissions/new...czy muszę stworzyć nowy formularz do tego? Bo do istniejącego formularza dodałam:
= simple_form_for @article do |a|
  = a.input :DOI, label: "Numer DOI"

albo:
= f.fields_for :article, @article.DOI do |doi|
    = doi.input :DOI, label: "Numer DOI"

i odpowiednie zmiany w controllerze, ale nie działa a nie mam innego pomysłu. Insert w tym formularzu jest tylko do submission a potrzebny jest insert do innej tabeli. Czy to w ogóle nie ma być w tym miejscu?

**Comment by apohllo** [comment]
Zmiany powinny być w articles_controller a nie submissions_controller. Poza tym DOI w kodzie musi być pisany małymi literami: :doi.

**Comment by apohllo** [comment]
DOI jako atrytub `Article` już jest w bazie danych. Trzeba tylko rozszerzyć formularz edycji artykułów, w `articles_controller`.
