### ISSUE TITLE
Wysyłanie przypomnienia o konieczności złożenia ankiety

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#85]
System powinien generować przypomnienie dla redaktora, że w lipcu konieczne jest złożenie ankiety.

**Comment by ghost** [comment]
zajmuję

**Comment by ghost** [comment]
A za ile jest punktów? :)

**Comment by apohllo** [comment]
Wstrzymałem się z przypisaniem, bo tego nie da się zrobić w samych Railsach... Ponegocjujemy ;-)
