### ISSUE TITLE
Widget wyboru daty przy edycji recenzji

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#86]
W formularzu recenzji edycja daty nadesłania recenzji powinna być aktywować "widget", w którym znajduje się kalendarz pozwalający na wybór konkretnej daty.

**Comment by robson3999** [comment]
Zaklepuje

**Comment by apohllo** [comment]
Jeśli ten widget zostanie dodany do następujących elementów:
- `Data początkowa` w filtrowaniu zgłoszeń
- `Otrzymano` przy edycji zgłoszeń
- `Deadline` przy edycji recenzji

to zadanie będzie rozliczone za 2 punkty.
