### ISSUE TITLE
Filtorwanie osób po typie

### ISSUE THREAD

**Issue by apohllo** [apohllo/rocznik#9]
W widoku osób powinna być możliwość filtrowania po typie (tzn. autor/recenzent/redaktor).
Filtrowanie powinno być zapamiętywane, tzn. przejście do innej części systemu i powrót do widoku osób powinno wyświetlić tylko osoby określonego typu. Powinna również istnieć możliwość wyłączenia filtrowania.

**Comment by AdriannaDab** [comment]
Wstępnie rezerwuje
